#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
/home/kache/.screenlayout/triple.sh

bspc monitor %DP-0.8 -d 1 2 3 4 5 6 7 8 9 
bspc monitor %DP-2 -d 1 2 3 4 5 6 7 8 9 
bspc monitor %DP-0.1.8 -d 1 2 3 4 5 6 7 8 9 

bspc monitor %DP-0.1.8 -n 3  
bspc monitor %DP-2 -n 2
bspc monitor %DP-0.8 -n 1

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config pointer_follows_focus       true
bspc config remove_disabled_monitors    true
bspc config pointer_action1             move
bspc config pointer_action3             resize_side 
bspc config pointer_action3             resize_corner
bspc config directional_focus_tightness low


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

nitrogen --restore &
